#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          harvey,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorF,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorX,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motory,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int encoderval=8000;
	int enableMask=1;

	bool mD = false;
	bool mE = false;
	bool mF = false;
	bool mG = true;

	if (mD) {
		motor[motorD]=75;
		while(nMotorEncoder[motorD]<encoderval){}
		motor[motorD]=0;
		wait10Msec(300);
	}


	if (mE) {
		motor[motorE]=75;
		while(nMotorEncoder[motorE]<encoderval){}
		motor[motorE]=0;
		wait10Msec(300);
	}

	if (mF) {
		motor[motorF]=75;
		while(nMotorEncoder[motorF]<encoderval){}
		motor[motorF]=0;
		wait10Msec(300);
	}

	if (mG) {
		motor[motorG]=75;
		while(nMotorEncoder[motorG]<encoderval){}
		motor[motorG]=0;
	}
}
