#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorF,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo12,              tServoNone)

//*!!Code automatically generated by '7gROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#include "/basic_move_header.h"

void hitpole(){
	motor[motorD]=-100;
	motor[motorE]=-100;
	motor[motorF]=-100;
	motor[motorG]=-100;
	wait1Msec(1250);
	motor[motorD]=50;
	motor[motorE]=50;
	motor[motorF]=50;
	motor[motorG]=50;
	wait1Msec(1500);
	motor[motorD]=-100;
	motor[motorE]=-100;
	motor[motorF]=-100;
	motor[motorG]=-100;
	wait1Msec(1000);
	wheel_stop();
}
//112896
//370881
//483777
void move_pos1(){
	//	playSound(soundBeepBeep);
		turn_rht(40,50);
		move_bck(40,700);
		turn_lft(40,145);
		hitpole();
}
void move_pos2(){

		move_bck(40,310);
		turn_rht(40,50);
		hitpole();
}
void move_pos3(){
	playSound(soundBeepBeep);
		turn_rht(40,100);
		move_bck(40,370);
		turn_lft(40,100);
		hitpole();
}


// main task
task main (){
	short position = 0;
	short value = 0;

	//variables for counting how many times a position has been recorded
	short pos1count = 0;
	short pos2count = 0;
	short pos3count = 0;

	//how many times you need to reed a value for each pos
	short epsilon1 =2;
	short epsilon2 = 5;
	short epsilon3= 5;

	//moves to read sensor value
	move_bck(40, 700);

	//loops until finished deciding center goal pos
	while(true)
	{
		//waits to initialize sensor
		wait1Msec(1000);

		//obtains ir sector reading
		value = SensorValue[IR];

		//displays what the current ir sector reading is
		displayTextLine(1, "%d", value);

		//Finding what position it currently reads, it will have to read
		//the same value a number of times before the program decides that
		//it is the correct positon
		if(value==5)
			pos3count++;
		else if(value==3)
			pos2count++;
		else
			pos1count++;

		//Deciding on a position, or deciding to do more testing
		if(pos1count>epsilon1){
			position = 1;
			break;
		}if(pos2count>epsilon2){
			position = 2;
			break;
		}if(pos3count>epsilon3){
			position = 3;
			break;
		}

	}
	//moves based on the location of the center goal
	if(position == 1){
		move_pos1();
	}
	else if(position == 2){
		nxtDisplayCenteredTextLine(3,"Reached Move_Pos2");
		move_pos2();
  }else if(position == 3){
		move_pos3();
	}
while(true){}
}
